#-------------------------------
# General Site Settings
title: WTMO
logo: /main/logo.jpg # You can add own logo.
description: WTMO theme for Jekyll


#-------------------------------
# Author Settings
author:
  name: 명정희
  image-main: /main/main2.jpg
  image: /main/profile.jpg
  image-s: /main/profile-s.jpg
  say-hello: 안녕하세요 저는 <strong>명정희</strong> 입니다.
  bio: 전공:&nbsp언어학<br/>연락처:&nbsp010-1234-1234
  # bio: Designs, talks, and writes about <strong>web</strong>, <strong>ethics</strong>, <strong>privacy</strong>, and dev. I share design tutorials, free resources and inspiration. Loves <a href="#">music</a> & riding his bicycle.


#-------------------------------
# Contact links
facebook: https://facebook.com/ # Add your Facebook handle
instagram: https://instagram.com/ # Add your Instagram handle


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
